http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  exchangeData:
    host: "localhost"
    paths: "/api/*"

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  exchange:
    url: 'https://zany-space-journey-g4x55xrg6qpgfwjgp-3000.app.github.dev/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  
  exchange:
    apiEndpoints:
      - exchangeData
    policies:
      - log:
          action:
            message: "${req.method} ${req.originalUrl}"
      - proxy:
          - action:
              serviceEndpoint: exchange
              changeOrigin: true
